Develop merge to master :: v1.2
misdwss/punjab-mgramseva pull request #381
Opened 2022-09-01 04:16 UTC by Ramkrishna-egov

2022-09-15 05:30 UTC, sirishrao-egov commented on business-services/billing-service/src/main/java/org/egov/demand/service/BillServicev2.java
> -				if (billAmount.compareTo(BigDecimal.ZERO) >= 0) {
what is the reason for removing the if condition here

2022-09-15 05:33 UTC, sirishrao-egov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                        if(additionalDetails.get(CHALLAN_NO_ADDITIONAL_FIELD_NAME) != null) {
additionalDetails needs to be null checked before using get function

2022-09-15 05:34 UTC, sirishrao-egov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                if(!applicationNumbersFromDemands.contains(calculation.getChallan().getChallanNo()))
calculation is not null safe

2022-09-15 05:35 UTC, sirishrao-egov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                String consumerCode = calculation.getChallan().getReferenceId();
calculation is not null safe

2022-09-15 05:35 UTC, sirishrao-egov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            String consumerCode = calculation.getChallan().getReferenceId();
calculation.getChallan() is not null safe

2022-09-15 05:35 UTC, snehal-eGov commented on business-services/billing-service/src/main/java/org/egov/demand/service/BillServicev2.java
> -				if (billAmount.compareTo(BigDecimal.ZERO) >= 0) {
Because otherwise it will not generate bills for advance amount. which is less than 0.

2022-09-15 05:36 UTC, sirishrao-egov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            List<Demand> searchResult = searchDemand(calculation.getTenantId(),
calculation is not null safe

2022-09-15 06:17 UTC, sirishrao-egov commented on municipal-services/echallan-services/src/main/java/org/egov/echallan/repository/ChallanRepository.java
> +		for (Challan challan : challans) {
would there be atleast one challan object in the challans. If not then make it null safe.

2022-09-15 06:21 UTC, sirishrao-egov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +					if(demandRequest.getDemands().isEmpty()) {
Did'nt get the reason of this code. Because you are clearing the object already and later checking if it's empty.

2022-09-15 06:25 UTC, sirishrao-egov commented on municipal-services/ws-calculator/src/main/java/org/egov/wscalculation/service/PayService.java
> +		if(type.equalsIgnoreCase("FIXED") && rate != null) {
FIXED - should not be hardcoded.
subType.equalsIgnoreCase(WSCalculationConstant.PENALTY_CURRENT_MONTH) should be reverse like 
WSCalculationConstant.PENALTY_CURRENT_MONTH.equalsIgnoreCase(subType)

2022-09-15 06:27 UTC, sirishrao-egov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/repository/rowmapper/OpenWaterRowMapper.java
> +                currentWaterConnection.setPaymentType(rs.getString("paymentType"));
remove hardcoding

2022-09-15 06:27 UTC, sirishrao-egov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/repository/rowmapper/WaterRowMapper.java
> +                currentWaterConnection.setPaymentType(rs.getString("paymentType"));
remove hardcoding

2022-09-15 06:29 UTC, sirishrao-egov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/service/WaterServiceImpl.java
> +				.equalsIgnoreCase(WCConstants.PAYMENT_TYPE_ARREARS)) {
waterConnectionRequest.getWaterConnection().getPaymentType()
				.equalsIgnoreCase(WCConstants.PAYMENT_TYPE_ARREARS) --- reverse the condition check
				and null check shud happen till waterConnectionRequest.getWaterConnection()

2022-09-15 06:30 UTC, sirishrao-egov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/service/WaterServiceImpl.java
> +		if (waterConnectionRequest.getWaterConnection().getPaymentType()!=null && waterConnectionRequest.getWaterConnection().getPaymentType()
reverse the comparison

2022-09-15 06:31 UTC, snehal-eGov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +					if(demandRequest.getDemands().isEmpty()) {
Not removing all, removing only the ones from demandListToRemove

2022-09-15 06:32 UTC, snehal-eGov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +					if(demandRequest.getDemands().isEmpty()) {
So the demand list might still have demands

2022-09-15 06:33 UTC, snehal-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            List<Demand> searchResult = searchDemand(calculation.getTenantId(),
@rahu-eGov

2022-09-15 06:34 UTC, snehal-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            String consumerCode = calculation.getChallan().getReferenceId();
@rahu-eGov

2022-09-15 06:34 UTC, snehal-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                        if(additionalDetails.get(CHALLAN_NO_ADDITIONAL_FIELD_NAME) != null) {
@rahu-eGov

2022-09-15 06:34 UTC, snehal-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                if(!applicationNumbersFromDemands.contains(calculation.getChallan().getChallanNo()))
@rahu-eGov

2022-09-15 06:35 UTC, snehal-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                String consumerCode = calculation.getChallan().getReferenceId();
@rahu-eGov

2022-09-15 06:35 UTC, snehal-eGov commented on municipal-services/echallan-services/src/main/java/org/egov/echallan/repository/ChallanRepository.java
> +		for (Challan challan : challans) {
@rahu-eGov

2022-09-15 06:36 UTC, snehal-eGov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +					if(demandRequest.getDemands().isEmpty()) {
and only if it has demands, we will push the event, otherwise we will not

2022-09-15 06:38 UTC, snehal-eGov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/repository/rowmapper/OpenWaterRowMapper.java
> +                currentWaterConnection.setPaymentType(rs.getString("paymentType"));
this method is followed for all rowmappers.. passing table column names. cannot add all of these to constants

2022-09-15 06:38 UTC, snehal-eGov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/repository/rowmapper/WaterRowMapper.java
> +                currentWaterConnection.setPaymentType(rs.getString("paymentType"));
this method is followed for all rowmappers.. passing table column names. cannot add all of these to constants

2022-09-15 06:38 UTC, snehal-eGov commented on municipal-services/ws-calculator/src/main/java/org/egov/wscalculation/service/PayService.java
> +		if(type.equalsIgnoreCase("FIXED") && rate != null) {
will fix this

2022-09-15 06:39 UTC, snehal-eGov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/service/WaterServiceImpl.java
> +				.equalsIgnoreCase(WCConstants.PAYMENT_TYPE_ARREARS)) {
will fix this

2022-09-15 06:39 UTC, snehal-eGov commented on municipal-services/ws-services/src/main/java/org/egov/waterconnection/service/WaterServiceImpl.java
> +		if (waterConnectionRequest.getWaterConnection().getPaymentType()!=null && waterConnectionRequest.getWaterConnection().getPaymentType()
will fix this

2022-09-15 06:50 UTC, sirishrao-egov requested changes
have added my comments, please check

2022-09-15 06:50 UTC, sirishrao-egov requested changes
have added my comments, please check

2022-09-15 08:25 UTC, snehal-eGov commented
Addressed the changes @sirishrao-egov

2022-09-16 04:49 UTC, rahu-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            String consumerCode = calculation.getChallan().getReferenceId();
There was challan transfer and checked other way around.
https://github.com/misdwss/punjab-mgramseva/blob/fcc28b30600ce8b2b5c70168f7777b0453122cdf/municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java#L120

https://github.com/misdwss/punjab-mgramseva/blob/fcc28b30600ce8b2b5c70168f7777b0453122cdf/municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java#L128

2022-09-16 05:23 UTC, rahu-eGov commented on municipal-services/echallan-services/src/main/java/org/egov/echallan/repository/ChallanRepository.java
> +		for (Challan challan : challans) {
@NotNull annotation for parameter null check. So responsibility of calling function to check parameter is not null.
Loop will not break even there is no element.

2022-09-16 07:02 UTC, rahu-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                        if(additionalDetails.get(CHALLAN_NO_ADDITIONAL_FIELD_NAME) != null) {
Null check has been added. Please review

2022-09-16 07:03 UTC, rahu-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                if(!applicationNumbersFromDemands.contains(calculation.getChallan().getChallanNo()))
Null check has been added. Please review

2022-09-16 07:03 UTC, rahu-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +                String consumerCode = calculation.getChallan().getReferenceId();
Null check has been added. Please review

2022-09-16 07:03 UTC, rahu-eGov commented on municipal-services/echallan-calculator/src/main/java/org/egov/echallancalculation/service/DemandService.java
> +            List<Demand> searchResult = searchDemand(calculation.getTenantId(),
Null check has been added. Please review

2022-09-16 07:42 UTC, sirishrao-egov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +					if(demandRequest.getDemands().isEmpty()) {
agreed

2022-09-20 04:56 UTC, sirishrao-egov approved these changes
Review changes are adapted

2022-09-20 06:50 UTC, sathishp-eGov approved these changes

2022-09-20 06:50 UTC, merged