Demand update event
misdwss/punjab-mgramseva pull request #395
Opened 2022-10-18 11:57 UTC by snehal-eGov

2022-10-21 05:24 UTC, sirishrao-egov requested changes

2022-10-21 05:24 UTC, sirishrao-egov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +						else if(demand.getStatus().toString().equalsIgnoreCase(Constants.ACTIVE) && demandDetails != null){
demand.getStatus().toString().equalsIgnoreCase(Constants.ACTIVE)
Please swap the comparison with constant as outside

2022-10-21 05:24 UTC, sirishrao-egov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +								DemandDetail demanddetail = demandDetails.get(demandDetails.size()-1);
@snehal-eGov  : get(demandDetails.size()-1) --- if demandsize is 0 then it will be get(-1)? Please check this

2022-10-21 05:24 UTC, sirishrao-egov commented on municipal-services/mgramseva-ifix-adapter/src/main/java/org/egov/mgramsevaifixadaptor/consumer/MgramsevaAdapterDemandConsumer.java
> +									demand.getDemandDetails().remove(i);
@snehal-eGov : Please explain what this for loop and code with-in does

2022-10-25 05:30 UTC, egov-arindam approved these changes

2022-10-25 05:30 UTC, merged