V1.2.1+19
misdwss/punjab-mgramseva pull request #424
Opened 2023-01-18 08:09 UTC by Ramkrishna-egov

2023-01-18 10:39 UTC, naveen-egov requested changes

2023-01-18 10:39 UTC, naveen-egov commented on frontend/mgramseva/lib/screeens/Home/Home.dart
>                      "limit": "50"
Move limit to constants

2023-01-18 10:45 UTC, naveen-egov approved these changes

2023-01-19 10:09 UTC, egov-arindam approved these changes

2023-01-19 10:09 UTC, merged